import './utils/random-array.js';
import './data.js';
import './utils/random-array.js';
import './data.js';
import './form-validation.js';
import './address-choosing.js';
import './ads-comparation.js';
import './card-creation.js';
import './map.js';
